"use strict"
!function(){function e(e,t){return this.dom=e,this.settings=t,this.bibjson=[],this.bibtex="",this.load()}jQuery.fn.publication=function(t){var n=this.data("plugin_publication")
return n||(n=new e(this,jQuery.extend(!0,{},jQuery.fn.publication.defaultSettings,t||{})),this.data("plugin_publication",n)),n},jQuery.fn.publication.defaultSettings={bibjson:null,bibtex:null,csshidden:"hidden",cssvisible:"visible",cssentry:"publication",datafield:"bibtexid",crossdomain:!1,callbackEntryGenerator:function(e){return jQuery("<li>")},callbackIDGenerator:function(e){var t=e.dom.attr("id")
if(!t)throw new Error("parent object needs an id attribute")
return function(e){return t+"-"+e.replace(/[^a-z0-9\-_]|^[^a-z]+/gi,"_")}},callbackFinish:null,callbackEntry:{0:function(e,t){var n=jQuery('<span class="title">')
return n.append(t.URL?jQuery("<a>").attr("href",t.URL).append(t.title+"."):t.title+"."),t.DOI&&n.append(" (").append(jQuery("<a>").attr("href","https://doi.org/"+t.DOI).attr("target","_blank").html("DOI")).append(")"),n},10:function(e,t){if(!t.author)return null
var n=jQuery('<span class="author">')
return n.append(t.author.map(function(e){return e.given&&e.family?e.family+(e["dropping-particle"]?" "+e["dropping-particle"]:"")+", "+e.given+".":e.literal?e.literal:null}).filter(function(e){return null!=e}).join(", ")),n},20:function(e,t){var n=jQuery('<span class="publishing">'),i=[]
return t["container-title"]&&i.push(t["container-title"]),t["collection-number"]&&i.push("number "+t["collection-number"]),t.issue&&t.issued&&i.push(t.issue+"."+(jQuery.isNumeric(t.issue)?"":" ")+t.issued["date-parts"].map(function(e){return e.join(" ")})),t.volume&&i.push("volume "+t.volume),t.page&&i.push("page "+t.page),t.publisher&&i.push(t.publisher),0==i.length?null:(n.append(i.join(", ")),n)},30:function(e,t){if(!t.editor)return null
var n=jQuery('<span class="editor">')
return n.append(t.editor.map(function(e){return e.given&&e.family?e.family+(e["dropping-particle"]?" "+e["dropping-particle"]:"")+", "+e.given[0]+".":null}).filter(function(e){return null!=e}).join(", ")),n},40:function(e,t){var n=jQuery("<p>").attr("class","publicationtext")
n.append(jQuery("<a>").attr("name","#publication-"+t.id).attr("href","/publications/#publication-"+t.id).attr("title",t.id).append("&#128206;&nbsp;&nbsp;")),n.append(jQuery("<em>").append(t.author.map(function(e){return e.given&&e.family?e.family+(e["dropping-particle"]?" "+e["dropping-particle"]:"")+", "+e.given[0]+".":e.literal?e.literal:null}).filter(function(e){return null!=e}).join("; "))),n.append(" ("+(t.issued?t.issued["date-parts"][0][0]:"")+"). "),n.append(t.URL?jQuery("<a>").attr("href",t.URL).append(t.title+"."):t.title+"."),t.DOI&&n.append(" (").append(jQuery("<a>").attr("href","https://doi.org/"+t.DOI).attr("target","_blank").html("DOI")).append(").")
var i=[]
return t["container-title"]&&i.push(t["container-title"]),t["collection-number"]&&i.push("number "+t["collection-number"]),t.issue&&t.issued&&i.push(t.issue+"."+(jQuery.isNumeric(t.issue)?"":" ")+t.issued["date-parts"].map(function(e){return e.join(" ")})),t.volume&&i.push("volume "+t.volume),t.page&&i.push("page "+t.page),t.publisher&&i.push(t.publisher),i.length>0&&(i[0]=i[0].substr(0,1).toUpperCase()+i[0].substr(1),n.append(" "+i.join(", ")+".")),t.editor&&n.append(" Eds: ").append(t.editor?t.editor.map(function(e){return e.given&&e.family?e.family+(e["dropping-particle"]?" "+e["dropping-particle"]:"")+", "+e.given[0]+".":null}).filter(function(e){return null!=e}).join(", "):""),t.note&&n.append(" ").append(jQuery("<a>").attr("href",t.note).html("[&#8594; read more]")),n}}},e.prototype={load:function(){var e=this
return e.settings.bibjson&&jQuery.ajax({url:e.settings.bibjson,datatype:"json",crossdomain:e.settings.crossdomain}).done(function(n){e.bibjson={},n.forEach(function(t){e.bibjson[t.id]=t}),e.settings.bibtex?jQuery.get(e.settings.bibtex,"text").done(function(n){e.bibtex=n.replace(/\s+/g," ").replace(/\} @/g,"}\n@"),t(e)}).fail(function(){throw new Error("BibTeX source ["+e.settings.bibtex+"] cannot be read")}):t(e)}).fail(function(){throw new Error("BibJSON source ["+e.settings.bibjson+"] cannot be read")}),this},filter:function(e){var t=this,n=t.settings.callbackIDGenerator(this),i=e&&"function"==typeof e?e:function(){return!0}
return Object.values(this.bibjson).forEach(function(e){var r=n(e.id)
r&&(i(e)?jQuery("#"+r).removeClass(t.settings.csshidden).addClass(t.settings.cssvisible):jQuery("#"+r).addClass(t.settings.csshidden).removeClass(t.settings.cssvisible))}),this},sort:function(e){var t=this,n=e&&"function"==typeof e?e:function(){return 0}
return this.dom.children().sort(function(e,i){return n(t.bibjson[jQuery(e).data(t.settings.datafield)],t.bibjson[jQuery(i).data(t.settings.datafield)])}).appendTo(this.dom),this},bibtexsource:function(e){var t=new RegExp("@.+\\{"+e.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")+"(.|\\s)+?(@|$)").exec(this.bibtex)
if(!t||0==t.length)return null
var n=t[0].slice(0,-1).trim()
return"}"!=n[n.length-1]?n+"}":n}}
var t=function(e,t){if("function"!=typeof e.settings.callbackIDGenerator)throw new Error("ID generator not set")
if("function"!=typeof e.settings.callbackEntryGenerator)throw new Error("entry generator callback not set")
var i=e.settings.callbackIDGenerator(e),r=e.settings.bibtex?function(t){if(!new RegExp("@.+\\{"+t.id.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")).test(e.bibtex))throw new Error("BibJSON ID ["+t.id+"] not found in BibTeX source, data sources seems not be synchronized")
return t}:function(e){return e}
e.dom.empty(),Object.values(e.bibjson).map(r).forEach(function(t){e.dom.append(n(e,i,t))}),"function"==typeof e.settings.callbackFinish&&e.settings.callbackFinish(e)},n=function(e,t,n){var i=e.settings.callbackEntryGenerator(n)
return i.attr("data-"+e.settings.datafield,n.id).attr("id",t(n.id)).addClass(e.settings.cssentry).addClass(e.settings.cssvisible),n.type&&i.addClass(n.type.replace(/[^a-z0-9\-_]|^[^a-z]+/gi,"_")),Object.values(e.settings.callbackEntry).forEach(function(t){var r=t(e,n)
r&&i.append(" ").append(r)}),i}}(jQuery),jQuery(function(){jQuery("#publication").publication({bibjson:"/references.json",bibtex:"/references.bib",callbackEntry:{50:function(e,t){var n=e.settings.callbackIDGenerator(e)
return jQuery("<a>").addClass("bibtex").attr("href","#"+n(t.id)).attr("data-clipboard-text",e.bibtexsource(t.id)).attr("title","copy BibTeX entry '"+t.id+"' to clipboard").text("📋 BibTeX")}},callbackFinish:function(e){new Clipboard("#giveall",{text:function(){return jQuery(".visible > a").filter(function(e,t){return-1===jQuery(t).parent().attr("class").indexOf("hidden")}).map(function(e,t){return jQuery(t).data("clipboard-text")}).get().join("\n")}}).on("success",function(e){alert("BibTeX Entries copied to Clipboard"),e.clearSelection()}),new Clipboard(".bibtex").on("success",function(e){alert("BibTeX Entry copied to Clipboard"),e.clearSelection()}),e.sort(function(e,t){if(e.issued["date-parts"][0][0]>t.issued["date-parts"][0][0])return-1
if(e.issued["date-parts"][0][0]<t.issued["date-parts"][0][0])return 1
var n=e.author.map(function(e){return e.given&&e.family?e.family+(e["dropping-particle"]?" "+e["dropping-particle"]:"")+", "+e.given[0]+".":e.literal?e.literal:null}).filter(function(e){return null!=e}).join("; ").localeCompare(t.author.map(function(e){return e.given&&e.family?e.family+(e["dropping-particle"]?" "+e["dropping-particle"]:"")+", "+e.given[0]+".":e.literal?e.literal:null}).filter(function(e){return null!=e}).join("; "))
return 0!=n?n:e.title.localeCompare(t.title)})}})
var e=function(){var e=jQuery("#search").val()
if(!e||e.length<3)jQuery("#publication").publication().filter()
else{var t=e.split(/(\s+)/).filter(function(e){return e.trim().length>0})
jQuery("#publication").publication().filter(function(e){return["title","publisher","collection-title"].some(function(n){return e[n]&&(jQuery("#and").is(":checked")?t.every(function(t){return-1!=e[n].toLowerCase().indexOf(t.toLowerCase())}):t.some(function(t){return-1!=e[n].toLowerCase().indexOf(t.toLowerCase())}))})||["author","editor"].some(function(n){return e[n]&&(jQuery("#and").is(":checked")?t.every(function(t){return e[n].some(function(e){return e.family&&-1!=e.family.toLowerCase().indexOf(t.toLowerCase())||e.given&&-1!=e.given.toLowerCase().indexOf(t.toLowerCase())})}):t.some(function(t){return e[n].some(function(e){return e.family&&-1!=e.family.toLowerCase().indexOf(t.toLowerCase())||e.given&&-1!=e.given.toLowerCase().indexOf(t.toLowerCase())})}))})})}}
jQuery("#search").on("change keyup paste",e),jQuery("#and").change(e),jQuery("#or").change(e),["thesis","paper-conference","chapter","book","article-journal"].forEach(function(e){jQuery("#"+e).change(function(){jQuery(".publication:not(."+e+")").addClass("hidden"+e),["thesis","paper-conference","chapter","book","article-journal"].filter(function(t){return t!==e}).forEach(function(e){jQuery(".publication:not(."+e+")").removeClass("hidden"+e)})})}),jQuery("#all").change(function(){["thesis","paper-conference","chapter","book","article-journal"].forEach(function(e){jQuery(".publication:not(."+e+")").removeClass("hidden"+e)})}),$(document).ready(function(){jQuery("#search").focus()})})
