"use strict"
!function(){function t(t,e){return this.dom=t,this.settings=e,c(this)}jQuery.fn.teletype=function(e){var s=this.data("plugin_teletype")
return s||(s=new t(this,jQuery.extend({},jQuery.fn.teletype.defaultSettings,e||{})),this.data("plugin_teletype",s)),s},jQuery.fn.teletype.defaultSettings={text:[],result:[],automaticstart:!0,classresult:"teletype-result",classprefix:"teletype-prefix",classcursor:"teletype-cursor",classoutput:"teletype-text",taglinebreak:"<br/>",typeDelay:120,backDelay:180,blinkSpeed:1e3,cursor:"|",prefix:"",loop:1,humanise:!0,smoothBlink:!0,callbackNext:null,callbackType:null,vallbackBackward:null,callbackFinished:null,callbackStart:null,callbackReset:null,callbackNextLoop:null},t.prototype={cursor:function(t){return this.settings.cursor=t,this.dom.find("."+this.settings.classcursor+":first").html(this.settings.cursor),this},reset:function(){return 0===this.settings.loop?this:(e(s(this.stop().empty())),"function"==typeof this.settings.callbackReset&&this.settings.callbackReset(this),this)},empty:function(){return this.dom.find("."+this.settings.classoutput+":first").empty(),this},stop:function(){return this.current.timeout&&clearTimeout(this.current.timeout),this},start:function(){return this.settings.automaticstart?this:(e(this),"function"==typeof this.settings.callbackStart&&this.settings.callbackStart(this),o(this),this)}}
var e=function(t){return t.settings.text&&0!==t.settings.text.length?(t.current.string=t.settings.text[t.current.index].replace(/\n/g,"\\n"),t.current.letters=t.current.string.split(""),t.current.result=t.settings.result.length===t.settings.text.length&&t.settings.result[t.current.index]?'<p class="'+t.settings.classresult+'">'+t.settings.result[t.current.index]+"</p>":"",t):t},s=function(t){return t.current={string:"",result:"",letters:[],index:0,position:0,loop:0,timeout:null},t},n=function(t,e){return t.settings.humanise?Math.round(parseInt(e)+Math.random()*e/3):parseInt(e)},i=function(t,e){var s=t.substr(e).search(/[^0-9]/)
return t.substr(e,-1===s?t.length:s)},r=function(t,e){var s=i(t.current.string,e)
return jQuery.isNumeric(s)?(t.current.position=e+s.length,t.current.timeout=setTimeout(o(t),s),t):t},u=function(t){return t.current.index+=1,t.current.index>=t.settings.text.length&&(t.current.index=0,t.current.loop+=1,"function"==typeof t.settings.callbackNextLoop&&t.settings.callbackNextLoop(t),!1!==t.settings.loop&&t.settings.loop===t.current.loop)?("function"==typeof t.settings.callbackFinished&&t.settings.callbackFinished(t),!1):(e(t),t.current.position=0,"function"==typeof t.settings.callbackNext&&t.settings.callbackNext(t),!0)},c=function(t){if(t.dom.empty(),s(t),t.output=jQuery("<span/>").addClass(t.settings.classoutput).appendTo(t.dom),t.settings.cursor){var n=jQuery("<span/>").addClass(t.settings.classcursor).appendTo(t.dom).text(t.settings.cursor),i=t
setInterval(function(){i.settings.smoothBlink?n.animate({opacity:0}).animate({opacity:1}):n.delay(500).fadeTo(0,0).delay(500).fadeTo(0,1)},t.settings.blinkSpeed)}return t.settings.automaticstart&&(e(t),"function"==typeof t.settings.callbackStart&&t.settings.callbackStart(t),o(t)),t},l=function(t,e){return e<1||t.current.position-e<1?(t.current.timeout=setTimeout(o(t),n(t,t.settings.typeDelay)),t):(t.current.timeout=setTimeout(function(){t.output.html(t.output.html().slice(0,-1)),l(t,e-1),"function"==typeof t.settings.callbackBackward&&t.settings.callbackBackward(t)},n(t,t.settings.backDelay)),t)},o=function(t){t.settings.prefix&&0===t.current.position&&jQuery("<span />").addClass(t.settings.classprefix).html(t.settings.prefix).appendTo(t.output)
var e=t.current.letters[t.current.position],s=t.current.position+1
if("^"===e)return void r(t,s)
if("~"===e){var c=i(t.current.string,s)
if(jQuery.isNumeric(c)){var a=t
return t.current.position+=c.length+1,void(t.current.timeout=setTimeout(function(){l(a,c)},n(t,t.settings.backDelay*c)))}}"\\"===e&&"n"===t.current.string.substr(s,1)&&(t.current.position+=1,e=t.settings.taglinebreak),"function"==typeof t.settings.callbackType&&t.settings.callbackType(t),t.current.position<t.current.string.length?t.current.timeout=setTimeout(function(){t.current.position+=1,t.output.html(t.output.html()+e),o(t)},n(t,t.settings.typeDelay)):(t.current.result&&t.output.html(t.output.html()+t.current.result),u(t)&&(t.output.html(t.output.html()+t.settings.taglinebreak),t.current.timeout=setTimeout(o(t),n(t,t.settings.typeDelay))))}}(jQuery)
