version: 2

jobs:
    build:
        docker:
            - image: circleci/node:latest

        branches:
            only:
                - developing
            ignore:
                - master
                - /dev-.*/     

        shell: /bin/bash           


        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"

            GIT_AUTHOR_NAME: CircleCI
            GIT_AUTHOR_EMAIL: info@lightjason.org
            GIT_COMMITTER_NAME: CircleCI
            GIT_COMMITTER_EMAIL: info@lightjason.org



        steps:
            - checkout
            - run:
                name: Git Clean
                command: git clean -xdf
            - run:
                name: Git Remove Unused Branches
                command: git fetch -p
            - run:
                name: Git Prune
                command: git gc --prune=now
            # https://github.com/spf13/hugo/releases
            - run:
                name: Download Hugo
                command: wget -O /tmp/hugo.deb https://github.com/spf13/hugo/releases/download/v0.27.1/hugo_0.27.1_Linux-64bit.deb
            - run:
                name: Install Hugo
                command: sudo dpkg -i /tmp/hugo.deb
            # https://github.com/kangax/html-minifier    
            - run:
                name: Install HTML-Minifier
                command: npm install html-minifier
            # https://github.com/svg/svgo
            - run:
                name: Install SVGO
                command: npm install https://github.com/svg/svgo.git
            # https://github.com/fizker/minifier
            - run:
                name: Install Minifier
                command: npm install https://github.com/fizker/minifier.git
            - run:
                name: Build Hugo Website
                command: hugo --ignoreCache --cleanDestinationDir
            - run:
                name: Minify SVGs
                command: node_modules/svgo/bin/svgo --config=data/svgo.config public/images/
            - run:
                name: Minify HTML
                command: find public -type f -name "*.htm*" -exec data/minify.sh \{\} \;
            - run:
                name: Minify CSS
                command: find public -type f -name "*.css" -exec data/minify.sh \{\} \;
            - run:
                name: Minify JS
                command: find public -type f -name "*.js" -exec data/minifyjs.sh \{\} \;
            - run:
                name: Build Artifacts
                command: tar -cvjSf site.tar.bz2 public/*    
            - store_artifacts:
                path: site.tar.bz2
            - run:
                name: Moving Artifacts to Temporary
                command: mv -f public /tmp
            - run:
                name: Delete Remote Master Branch
                command: git push origin :master || true
            - run:
                name: Delete Local Master Branch
                command: git brach -D master || true  
            - run:
                name: Initialize Orphan Master Branch
                command: git checkout --orphan master
            - run:
                name: Remove Non-Usable Data
                command: rm -Rf *
            - run:
                name: Moving Artifacts back to Repository
                command: mv -f /tmp/public/* .
            - run:
                name: Create Circle-CI Configuration
                command: echo -e 'general:\n    branches:\n        ignore:\n            - master\n' > circle.yml
            - run:
                name: Create GitIgnore
                command: echo -e '*.*\n!.gitignore\n!circle.yml\n!*.html\n!*.xml\n!*.css\n!*.js\n!*.json\n!*.bib\n!*.zip\n!*.png\n!*.gif\n!*.pdf\n!*.svg\n!*.txt\n' > .gitignore
            - run:
                name: Create Readme
                command: echo -e '# LightJason\n\nCurrent website of the [LightJason](http://lightjason.org) project' > readme.md
            - run: 
                name: Git Branch Add
                command: git add --all .
            - run:
                name: Git Branch Commit
                command: GIT_COMMIT_MESSAGE="$(git show -s --pretty=format:%s $CIRCLE_SHA1)" && git commit -m "webpage update [$GIT_COMMIT_MESSAGE]"
            - run:
                name: Git Push
                command: git push origin master
